language: ruby
sudo: false
cache: bundler
rvm:
  # MRI
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  # Rubinius is failing due to segfaults on Travis (and takes significantly longer to run)
  # those builds will be restored later
  # jruby
  - jruby-19mode
bundler_args: --without development
addons:
  code_climate:
    repo_token: 7af99d9225b4c14640f9ec3cb2e24d2f7103ac49417b0bd989188fb6c25f2909
